-- MySQL Script generated by MySQL Workbench
-- Fri Mar  8 14:47:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Matcha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Matcha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Matcha` DEFAULT CHARACTER SET utf8 ;
USE `Matcha` ;

-- -----------------------------------------------------
-- Table `Matcha`.`genders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`genders` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`orientations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`orientations` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `orientation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Matcha`.`userStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`userStatus` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `userStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Matcha`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`users` (
  `ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(50) COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `password` VARCHAR(255) COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `lastName` VARCHAR(50) COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `firstName` VARCHAR(50) COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `email` VARCHAR(255) COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `validKey` VARCHAR(50) COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `birthDate` DATE NULL DEFAULT NULL,
  `shortBio` VARCHAR(255) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `profilePictureID` VARCHAR(50) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `userStatus` TINYINT(4) NULL DEFAULT '1',
  `online` TINYINT(4) NULL DEFAULT '0',
  `lastLog` DATETIME NULL DEFAULT NULL,
  `orientations_ID` INT(10) UNSIGNED NULL DEFAULT '1',
  `genders_ID` INT(10) UNSIGNED NULL DEFAULT NULL,
  `userStatus_ID` INT(10) UNSIGNED NULL DEFAULT '1',
  `longitude` DECIMAL(7,4) NULL DEFAULT NULL,
  `latitude` DECIMAL(7,4) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_users_FK_orientations1_idx` (`orientations_ID` ASC),
  INDEX `fk_users_FK_genders1_idx` (`genders_ID` ASC),
  INDEX `fk_users_FK_userStatus1_idx` (`userStatus_ID` ASC),
  CONSTRAINT `fk_users_FK_genders1`
    FOREIGN KEY (`genders_ID`)
    REFERENCES `Matcha`.`genders` (`ID`),
  CONSTRAINT `fk_users_FK_orientations1`
    FOREIGN KEY (`orientations_ID`)
    REFERENCES `Matcha`.`orientations` (`ID`),
  CONSTRAINT `fk_users_FK_userStatus1`
    FOREIGN KEY (`userStatus_ID`)
    REFERENCES `Matcha`.`userStatus` (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`likes` (
  `users_ID` INT(11) UNSIGNED NOT NULL,
  `liked_ID` INT(11) UNSIGNED NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`users_ID`, `liked_ID`),
  INDEX `fk_users_has_users_users2_idx` (`liked_ID` ASC),
  INDEX `fk_users_has_users_users1_idx` (`users_ID` ASC),
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`users_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`liked_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`viewed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`viewed` (
  `users_ID` INT(11) UNSIGNED NOT NULL,
  `viewed_ID` INT(11) UNSIGNED NOT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`users_ID`, `viewed_ID`),
  INDEX `fk_users_has_users1_users2_idx` (`viewed_ID` ASC),
  INDEX `fk_users_has_users1_users1_idx` (`users_ID` ASC),
  CONSTRAINT `fk_users_has_users1_users1`
    FOREIGN KEY (`users_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users1_users2`
    FOREIGN KEY (`viewed_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`tags` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `tag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`users_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`users_has_tag` (
  `users_ID` INT(11) UNSIGNED NOT NULL,
  `table1_ID` INT NOT NULL,
  PRIMARY KEY (`users_ID`, `table1_ID`),
  INDEX `fk_users_has_table1_table11_idx` (`table1_ID` ASC),
  INDEX `fk_users_has_table1_users1_idx` (`users_ID` ASC),
  CONSTRAINT `fk_users_has_table1_users1`
    FOREIGN KEY (`users_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_table1_table11`
    FOREIGN KEY (`table1_ID`)
    REFERENCES `Matcha`.`tags` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`blocked`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`blocked` (
  `users_ID` INT(11) UNSIGNED NOT NULL,
  `blocked_ID` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`users_ID`, `blocked_ID`),
  INDEX `fk_users_has_users_users4_idx` (`blocked_ID` ASC),
  INDEX `fk_users_has_users_users3_idx` (`users_ID` ASC),
  CONSTRAINT `fk_users_has_users_users3`
    FOREIGN KEY (`users_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users4`
    FOREIGN KEY (`blocked_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Matcha`.`reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Matcha`.`reports` (
  `users_ID` INT(11) UNSIGNED NOT NULL,
  `reported_ID` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`users_ID`, `reported_ID`),
  INDEX `fk_users_has_users_users6_idx` (`reported_ID` ASC),
  INDEX `fk_users_has_users_users5_idx` (`users_ID` ASC),
  CONSTRAINT `fk_users_has_users_users5`
    FOREIGN KEY (`users_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users6`
    FOREIGN KEY (`reported_ID`)
    REFERENCES `Matcha`.`users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Matcha`.`genders`
-- -----------------------------------------------------
START TRANSACTION;
USE `Matcha`;
REPLACE INTO `Matcha`.`genders` (`ID`, `gender`) VALUES (1, 'Undefined');
REPLACE INTO `Matcha`.`genders` (`ID`, `gender`) VALUES (2, 'Male');
REPLACE INTO `Matcha`.`genders` (`ID`, `gender`) VALUES (3, 'Female');
REPLACE INTO `Matcha`.`genders` (`ID`, `gender`) VALUES (4, 'Other');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Matcha`.`orientations`
-- -----------------------------------------------------
START TRANSACTION;
USE `Matcha`;
REPLACE INTO `Matcha`.`orientations` (`ID`, `orientation`) VALUES (1, 'Bisexual');
REPLACE INTO `Matcha`.`orientations` (`ID`, `orientation`) VALUES (2, 'Heterosexual');
REPLACE INTO `Matcha`.`orientations` (`ID`, `orientation`) VALUES (3, 'Homosexual');
REPLACE INTO `Matcha`.`orientations` (`ID`, `orientation`) VALUES (4, 'Other');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Matcha`.`userStatus`
-- -----------------------------------------------------
START TRANSACTION;
USE `Matcha`;
REPLACE INTO `Matcha`.`userStatus` (`ID`, `userStatus`) VALUES (1, 'Not verified');
REPLACE INTO `Matcha`.`userStatus` (`ID`, `userStatus`) VALUES (2, 'Half verified');
REPLACE INTO `Matcha`.`userStatus` (`ID`, `userStatus`) VALUES (3, 'Verified');
REPLACE INTO `Matcha`.`userStatus` (`ID`, `userStatus`) VALUES (4, 'Admin');

COMMIT;

